### ISSUE TITLE
Licence de la librairie graphique

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#1]
Le licence de la libraire [graphique](https://github.com/cspaier/thonny/blob/diderot/Thonny/Lib/site-packages/graphique.py) est floue.

La [version](https://www.pedagogie.ac-aix-marseille.fr/jcms/c_122350/fr/ressources-graphiques-pour-python) distribuée par l'Académie d'Aix-Marseille n'indique pas de licence mais présente l'en-tête suivante:
```
## Ce module a ete ecrit par Olivier Brebant en aout 2011
## On peut l'utiliser librement
```
Il faut contacter l'auteur et/ou l'académie pour obtenir l'autorisation de passer sous licence MIT ou compatible.

**Comment by al-coloic** [comment]
> Bonjour,
>
>nous sommes plusieurs professeurs de math du lycée diderot à reprendre la librairie graphque.py et >à  la développer  ici https://github.com/cspaier/thonny 
>
>La licence proposée en début de fichier est floue. Peut-on la changer pour une licence MIT ? Ou autre ?

>En vous remerciant pour le travail effectué.
>cdt
>rondon loic
  
 Envoyé via le formulaire de contact de la page [https://www.pedagogie.ac-aix-marseille.fr/jcms/c_122350/fr/ressources-graphiques-pour-python](https://www.pedagogie.ac-aix-marseille.fr/jcms/c_122350/fr/ressources-graphiques-pour-python )

**Comment by al-coloic** [comment]
Olivier Brébant a donné son accord par mail : on peut changer la licence en MIT
