### ISSUE TITLE
Raccourci vers u: ne fonctionne pas à la maison

### ISSUE THREAD

**Issue by zebobs** [Pydiderot/pydiderotIDE#11]
Le raccourci point vers "U:\Nouveau dossier\Thonny" ne peut pas fonctionner à la maison à cause du u:
De plus je pense qu'il y a une correction à faire (Nouveau dossier)

**Comment by cspaier** [comment]
Bien vu. Merci!

Faut que je regarde ca dans ma machine virtuelle.

**Comment by cspaier** [comment]
J'ai créé un fichier `.bat` pour faire un raccourci avec un chemin relatif.
