### ISSUE TITLE
Erreur au démarrage 

### ISSUE THREAD

**Issue by zebobs** [Pydiderot/pydiderotIDE#12]
Bonjour, 
j'ai ce message d'erreur au démarrage (ordi perso, windows10 à jour, droits d'admin sur cette session)

![image](https://user-images.githubusercontent.com/26971235/50116737-4aaa7a80-024b-11e9-90a1-695b3b0d3ae4.png)

**Comment by cspaier** [comment]
Bonjour,

Tu peux faire un copié/collé des erreurs s'il te plait?

**Comment by cspaier** [comment]
Apparamment [c'est réglé](https://bitbucket.org/plas/thonny/issues/467/error-when-running-thonny-with-pythonw) depuis thonny 2.2.

#13 devient urgent.

Merci pour le test et le retour.

**Comment by cspaier** [comment]
J'ai fait une branche avec thonny 3.0.8.

Si tu peux la télécharger [ici](https://github.com/cspaier/thonny/archive/thonny3.zip) et la tester ca serait parfait.

**Comment by zebobs** [comment]
Marche chez moi sur une config windows10 basique.

**Comment by cspaier** [comment]
Merci. Je mets ca au lycée à la rentrée.
