### ISSUE TITLE
Mise à jour de thonny

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#13]
[thonny évolue](https://thonny.org/blog/).

En particulier, la [première version stable](https://thonny.org/blog/2018/10/18/version_3_0_1.html) est sortie.

On peut espérer que cela répare #12 .

Peut-etre à faire pendant les vacances d'été?

**Comment by cspaier** [comment]
J'ai créé une branche [thonny3](https://github.com/cspaier/thonny/tree/thonny3) qui utilise thonny 3.0.8.

J'en ai profité pour installer pygame.

A tester. Il faudra ensuite adapter un peu la doc.

**Comment by cspaier** [comment]
Testé au lycée. Ca fonctionne.

**Comment by zebobs** [comment]
Peux tu confirmer que cela devient la branche principale ?

**Comment by cspaier** [comment]
Ca va la devenir. Il faut adapter un peu la doc. Je vais aussi en profiter pour rajouter des librairies manquantes (pygame, matplotlib, scipy) et tester tout ca.

Je préfère que la branche `diderot` soit toujours ce qui est installé au lycée.

En gros tu peux déja l'utiliser. Début janvier ca devient la branche principale et je l'installe au lycée.

**Comment by zebobs** [comment]
Testé sur une tablette PC d'un collègien de 3e.
C'est OK.

J'ai juste fait un hello word, il faudrait faire un fichier python test avec quelques accès librairies pour rendre les tests plus efficaces.

**Comment by cspaier** [comment]
Merci du retour.

Bonne idée le fichier test.

**Comment by cspaier** [comment]
@zebobs : J'ai mis thonny3 dans dev. C'était plus compliqué que prévu. Peux-tu tester la [nouvelle version](https://github.com/cspaier/pydiderot/archive/dev.zip) quand tu as le temps?

**Comment by zebobs** [comment]
Test de la branche dev à l'instant.
Erreur :
ModuleNotFoundError: No module named 'scipy'

**Comment by cspaier** [comment]
Merci.J'ai rajouté les libs mais c'est cassé :
```
ImportError: DLL load failed: Le module spécifié est introuvable.
```

![image](https://user-images.githubusercontent.com/44053087/50688421-b8b1b880-1025-11e9-9a16-8c97579ebc60.png)

**Comment by cspaier** [comment]
Bon en fait c'est un autre problème qui n'est pas lié à la mise à jour (voir #18 ).

Tu peux tester comme cela en attendant qu'on mette à jours le fichier de test:

```python
from graphique import *
from entree_tk import *

nom = demander_texte('Bonjour', "Quel est ton nom?")

age = demander_reel("Quel age as tu?")

annee = str(int(2019 - age))

creer_fenetre()
trace_texte(-5, 5, nom + " est né(e) en " + annee)

trace_point(5, 3)
trace_segment(-10, -4, 8, 7, couleur='red', taille = 2)
trace_rectangle(1, 1, 8, 4, couleur='black', taille = 4, remplissage='yellow')
trace_point(5, 5, couleur='blue',taille=5)
trace_point(6, 7, couleur='blue', taille=5, forme='croix')
    
affiche_fenetre()
```

**Comment by zebobs** [comment]
Ca fonctionne. (Mais "bonjour quel est ton nom" fait un peu peur)

**Comment by cspaier** [comment]
Si tu peux tester comme ca maintenant: `import TestLibrairies`

**Comment by cspaier** [comment]
J'ai créé une branche [thonny-2.1.17](https://github.com/cspaier/pydiderot/tree/thonny-2.1.17) qui contient l'ancienne version.

La branche `diderot` est à jour. Je teste demain au lycée.

**Comment by cspaier** [comment]
Testé au lycée. Ca fonctionne et j'ai installé la nouvelle version.
