### ISSUE TITLE
Fichier test

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#14]
Il serait bon de créer un fichier `test.py` qui utilise nos librairies maisons.

Ainsi, un utilisateur pourra rapidement vérifier que tout fonctionne et avoir un apercu de nos librairies.

**Comment by cspaier** [comment]
un début:
```python
from graphique import *
from entree_tk import *

nom = demander_texte('Bonjour', "Quel est ton nom?")

age = demander_reel("Quel age as tu?")

annee = str(int(2019 - age))

creer_fenetre()
trace_texte(-5, 5, nom + " est né(e) en " + annee)

trace_point(5, 3)
trace_segment(-10, -4, 8, 7, couleur='red', taille = 2)
trace_rectangle(1, 1, 8, 4, couleur='black', taille = 4, remplissage='yellow')
trace_point(5, 5, couleur='blue',taille=5)
trace_point(6, 7, couleur='blue', taille=5, forme='croix')

    
affiche_fenetre()
```

**Comment by al-coloic** [comment]
une [continuation](
    https://github.com/cspaier/thonny/blob/dev/Thonny/Lib/site-packages/TestLibrairies.py
      )

**Comment by cspaier** [comment]
Bien vu!

On documente et on ferme.

Astuce: Tu peux mentionner cette issue en écrivant `#14` dans le titre ou le commentaire de ton commit ;)

**Comment by al-coloic** [comment]
yep

reste la bibrairie stats et graphique_dynamique
