### ISSUE TITLE
Renommer le dépot

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#15]
En fait c'est plus "Python-diderot" que "thonny".

De plus, je suis pas comfortable d'avoir pris l'url https://thonny.readthedocs.io/.

Ca va changer l'url du dépot et de la doc. J'aimerai bien faire ca avant la rentrée et la formation pour éviter de diffuser des url qui vont bouger.

**Comment by al-coloic** [comment]
Pydiderot ? Diderot tout cours ?

Mais je me suis fait la même réflexion sur l'url : oui il faudrait la libérer.

**Comment by cspaier** [comment]
pydiderot j'aime bien :)
