### ISSUE TITLE
Documentation stats_proba

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#16]
Ca veut pas compiler :(

```
Thonny/Lib/site-packages/stats_proba.py:docstring of stats_proba.uniforme:1: WARNING: Inline literal start-string without end-string.
```

**Comment by al-coloic** [comment]
réessaye stp : j'ai changé une des apostrophes

**Comment by cspaier** [comment]
Nop, mais c'est bon. Sphinx interprète le `[` et `]`. Il faut les échapper `\[`.

Pour info la doc se met à jour automatiquement à partir de la branche dev.

**Comment by al-coloic** [comment]
Oui mais c'est bizarre que cela ne le fasse que sur la doc de 'uniforme' car il y a d'autres [ et ] ailleurs et on dirait que cela ne  pose pas de problème...

**Comment by cspaier** [comment]
Je confirme:
https://github.com/cspaier/pydiderot/blob/74771e0aa51c16e009f86544466199ee4ddc19ca/Thonny/Lib/site-packages/stats_proba.py#L53-L62

Franchement chercher à comprendre est une noble activitée qui peut s'avérer laborieuse et infructueuse. Si tu trouves tu nous dit. Pour l'instant la doc compile donc je serais pour fermer.
