### ISSUE TITLE
taille de l'environnement 0.5 GO!!!

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#19]
Je viens de télécharger au lycée:
- le zip fait 190 MO
- décompressé ca fait 540 MO

Bon, j'ai installe pygame, numpy, scipy et matplotlib, mais quand même!

Pour info, avec thonny 2.1.17 et sans les libs on était à 20 MO.

Donc, il faut vérifier qu'une installe propre de thonny avec les libs ci dessus prend grosso modo 540 MO (j'en doute). Tout ca sous windows dans ma virtual box... miam.

**Comment by cspaier** [comment]
Bon j'ai supprimé numpy, scipy et matplotlib:
- 26 MO compressé en zip
- 69 MO décompréssé

Tout ca avec pygame. le commit référencé ci dessus me fait un peu honte. Il faudra refaire des tests avec numpy.

En tout cas, on ferme!

**Comment by zebobs** [comment]
Matplotlib installe un numpy je crois

**Comment by cspaier** [comment]
Matplotlib a effectivement besoin de numpy mais en principe `pip` s'occupe plutot bien des dépendances (sous unix en tout ca).

En fait, les libs compilaient dans un dossier du genre `user/local/appdata`. Du coup j'ai copié/collé les libs compilées. J'ai du faire un test dans `Lib` et un autre dans `Lib/site-packages` et oublié d'en enlever un. 

D'où l'embarras!

Moralité: C'était quand même le bazar et il faudra refaire des tests pour numpy.

**Comment by al-coloic** [comment]
Recloner.
Ca pèse encore 180 Mo le truc ! Y a pas moyen d'alléger ?

**Comment by cspaier** [comment]
Si tu clones, il chope toutes les branches, les infos des commits et tout et tout.

L'utilisateur téléchargera un zip avec ce [lien](https://github.com/cspaier/thonny/archive/diderot.zip) qui contient uniquement les fichiers de la branche `diderot`.

**Comment by al-coloic** [comment]
199,7 Mo... :+1:

**Comment by cspaier** [comment]
Ok, ok ^^

La branche `diderot` est en retard de `dev` d'un certains nombres de commits. [Lien](https://github.com/cspaier/pydiderot/archive/dev.zip) dl de dev (26 MO).

De toute facon, pour l'instant, rien ne correspond à ce qu'il y a au lycée donc je me prennait pas la tête avec la branche `diderot`. Je vais merger pour éviter aux utilisateurs de pomper de la data pour rien.

**Comment by cspaier** [comment]
Bon juste pour dire qu'une install fraiche de thonny-3.0.8 avec pygame-1.9.4 et nos libs maisons pèse 82 MO non compressé.

Ca nous donne un repère pour la suite.
