### ISSUE TITLE
Rationaliser et documenter la librarie lycee

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#2]
La librairie [lycee](https://github.com/cspaier/thonny/blob/diderot/Thonny/Lib/site-packages/lycee.py) contient de nombreuses fonctions dont l'utilité n'est pas toujours claire.

L’intérêt de cette fonction par rapport à la fonction `range` de python ne m’apparait pas clairement par exemple:
https://github.com/cspaier/thonny/blob/4de3ed26fd274d69d54d2a1d93f6fadc06a4896c/Thonny/Lib/site-packages/lycee.py#L298-L314

Je pense qu'il faudra faire cela en même temps que la documentation. Fonction par fonction, évaluer l’intérêt. Si on la garde, on documente.

**Comment by cspaier** [comment]
Je vois pas mal de fonction du type 

https://github.com/cspaier/thonny/blob/9a27cb2f7dfd88543d82d97083d3e6dcfd16ffd4/Thonny/Lib/site-packages/lycee.py#L197-L203

C'est franchement inutile si on fait un import `from math import *` non?

**Comment by al-coloic** [comment]
non si on met les noms en français Square Root qui devient sqrt avec les futurs STMG ?
attention je vais forker !

**Comment by cspaier** [comment]
Un début [ici](https://github.com/cspaier/thonny/commit/c29015aedee8f92f147ef308d19864bc4de03d20) et de la doc [la](https://thonny.readthedocs.io/librairies/lycee_doc/).

**Comment by al-coloic** [comment]
je ferme car il me semble qu'on a fait le tour au moins sur la partie dév

**Comment by cspaier** [comment]
J'ouvre car on a un problème:

https://github.com/cspaier/pydiderot/blob/52d60062e8b26c3efde62848e74f827a731430c9/Thonny/Lib/site-packages/stats_proba.py#L423-L428

**Comment by al-coloic** [comment]
ouais... Cf. programme 2019 : [page 12](http://cache.media.eduscol.education.fr/file/Consultations2018-2019/78/6/PPL18_Mathematiques_COM_2e_1024786.pdf)

Il faut réécrire la librairie stats/proba

**Comment by cspaier** [comment]
ouaip. Globalement il y a encore du travail. On y trouves des mauvaise pratiques comme:

- fonctions acceptant un argument de type variable :
https://github.com/cspaier/pydiderot/blob/52d60062e8b26c3efde62848e74f827a731430c9/Thonny/Lib/site-packages/stats_proba.py#L180-L191

- fonctions retournant une valeur non typée:
https://github.com/cspaier/pydiderot/blob/52d60062e8b26c3efde62848e74f827a731430c9/Thonny/Lib/site-packages/stats_proba.py#L469-L475

- fonctions dont les paramètres influencent beaucoup trop la sortie ([KISS](https://fr.wikipedia.org/wiki/Principe_KISS)):
https://github.com/cspaier/pydiderot/blob/52d60062e8b26c3efde62848e74f827a731430c9/Thonny/Lib/site-packages/stats_proba.py#L248-L262

- C'est moins grave mais ca me gêne et je pense que c'est considéré comme mauvaise pratique d'initialiser une variable de type `int` avec le `str` `"optionel"`. Il est courant d'initialiser les variables à `None` ce qui permet ensuite de tester simplement `if var is None`.

**Comment by al-coloic** [comment]
on peut virer 'histop' et 'barre' : 

1. ce n'est pas au programme
2. geogebra fait  ça beaucoup mieux
3. c'est coder avec les pieds

**Comment by cspaier** [comment]
On est bon la non?

**Comment by al-coloic** [comment]
on est pas mal.

**Comment by cspaier** [comment]
On ferme alors!
