### ISSUE TITLE
bye bye numpy?

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#20]
Utiliser la librairie numpy est compliqué et [peu compatible avec l'utilisation de thonny](https://bitbucket.org/plas/thonny/wiki/InstallingPackages):

> Python distribution coming with Thonny doesn't contain scientific programming libraries (eg. NumPy and Matplotlib).
> 
> Recent versions of most popular scientific Python packages (eg. numpy, pandas and matplotlib) have wheels available for popular platforms so you can most likely install them with pip but in case you have troubles, you could try using Thonny with separate Python distribution meant for scientific computing (eg. Anaconda, Canopy or Pyzo).

Sauf erreur de ma part, la seule utilisation de numpy se trouve dans `lycee.stats_proba`. La qualité de cette librairie est discutée [ici](https://github.com/cspaier/pydiderot/issues/2#issuecomment-451780130) et nous envisageons de la recoder completement.

A savoir que se débarasser de numpy va résoudre #18 et #19.

Si quelqu'un veut numpy, qu'il s'exprime.

**Comment by al-coloic** [comment]
Mais également dans la librairie 'vecteur' : un vecteur est un numpy.array

**Comment by cspaier** [comment]
Bien vu. Avantages par rapport à une bonne vielle `list`?

**Comment by al-coloic** [comment]
aucun. Sauf dans la fonction 'norme' qui permet de faire v*v

**Comment by cspaier** [comment]
OK.
TODO: recoder `vecteurs` et `stats_proba` sans `numpy`.

**Comment by cspaier** [comment]
https://github.com/cspaier/pydiderot/projects/1

**Comment by zebobs** [comment]
Abandonner numpy ? 
Ne pas utilisé Array ?
c'est quand même la base en calcul scientifique. 
Ça peut être rigolo mais pas très réaliste à long terme.

**Comment by cspaier** [comment]
Je n'ai jamais utilisé python pour du calcul scientifique donc je ne me rend pas vraiment compte.

On envisage de faire faire du calcul scientifique en python aux élèves? On a géogebra pour ca non?

Si je résume notre utilisation actuelle de numpy:
- [Vecteurs](https://github.com/cspaier/pydiderot/blob/dev/Thonny/Lib/site-packages/vecteurs.py):  nos fonctions `norme`, `abscisse`,... fonctionnent tout pareil avec des listes.
- [Stats_proba](https://github.com/cspaier/pydiderot/blob/dev/Thonny/Lib/site-packages/stats_proba.py):
     - [Utilisation de matplotlib](https://github.com/cspaier/pydiderot/blob/5f2f2c0095f549bf6ab0626be4dee2414325a441/Thonny/Lib/site-packages/stats_proba.py#L15) pour construire des diagrammes statistiques (voir [ici](https://github.com/cspaier/pydiderot/issues/2#issuecomment-451831503)).
    - Utilisation de **[scipy.norm](https://github.com/cspaier/pydiderot/blob/5f2f2c0095f549bf6ab0626be4dee2414325a441/Thonny/Lib/site-packages/stats_proba.py#L13)** pour la loi normale.

On a un problème avec la loi normale.

@zebobs : As tu en tête un autre exemple concret d'utilisation dans un cadre pédagogique au secondaire qui nécessiterait numpy et les array en particulier?

**Comment by byache** [comment]
Perso, je viens de vérifier, même lors de la formation ISN où on avait un projet assez conséquent avec deux autres collègues, on n'avait presque pas utilisé numpy.
C'était des manipulations d'images en astronomie et des modif de pixels, on faisait tout avec des listes.
On avait seulement eu besoin de numpy pour "median" et "mean" sur des listes.
J'imagine qu'il y a des commandes "médiane" et "moyenne" dans les autres librairies...

**Comment by zebobs** [comment]
Numpy fait le traitement matriciel de façon très facile et très rapide.
Scipy utilise numpy. 

CV2 une bibliothèques de traitements d'images aussi.
Le seul test compliqué que j'ai fait est pour de la reconnaissance d'images avec cv2 et numpy.

Je pense que le but est également de pouvoir utiliser des bibliothèques sans trop de difficultés.
C'est intéressant d'utiliser des lists mais parfois des bibliothèques c'est bien !

**Comment by cspaier** [comment]
Bon, si je résume, on a pas de besoin urgent de numpy.

Il serait pratique de l'avoir sous le coude au cas ou.

Pour l'instant, j'arrive pas à avoir numpy portable qui fonctionne sur toutes les salles du lycée. Il semble qu'on soit obligé d'installer un autre environnement dédié à ca du type conda. Thonny peut utiliser un autre environement python. Mais ca va encore alourdir notre histoire. Donc il faudra peut-être envisager pyzo?

Après si quelqu'un peut fournir un thonny portable avec numpy testé sur les salles du lycée, on prend. J'ai pas réussi.

Bref je propose qu'on vire numpy qui fonctionne pas ce qui fixe #18 et #19. En attendant qu'on mette en place un autre environement, on recode nettoie `vecteurs` et `stats_proba` ce qui est à faire dans tous les cas.

Au moins, ca nous fait un truc qui fonctionne.

**Comment by zebobs** [comment]
C'est la bonne solution.
Je pense que ce n'est pas la priorité d'avoir numpy mais d'avoir qqch de fonctionnel.

**Comment by al-coloic** [comment]
la priorité c'est d'avoir GNU/linux !

**Comment by al-coloic** [comment]
On a vraiment besoin de : 
`
   def normal_frep(a, b, mu, sigma):
    """
    Renvoie un nombre décimal (float) représentant une estimation de la probabilité P(``a`` < X < ``b``)
    lorsque X suit une loi normale d'espérance ``mu`` et d'écart type ``sigma``.

    Arguments:
        a (float): Un nombre décimal
        b (float): Un nombre décimal
        mu (float): Un nombre décimal. L'espérance de la loi normale
        sigma (float): Un nombre décimal. L'écart type de la loi normale
    """
`

Geogebra fait ça très bien...

**Comment by cspaier** [comment]
Yup. Je vois pas trop l'intéret de faire ca sous python.

De toute facon, pour l'instant, on vire tout ce qui utilise numpy.

Par rapport à GNU/linux, il est vrai que le problème de DLL serait probablement résolu __au lycée__ sous linux. Par contre la majorité de nos élèves et professeurs utilisent Windows. Il est donc indispensable de fournir une version windows simplement fonctionnelle.

**Comment by al-coloic** [comment]
double oxymore :  

> une version windows simplement fonctionnelle

**Comment by al-coloic** [comment]
tester moyenne et ecart type. Si ça fonctionne on peut virer numpy

**Comment by al-coloic** [comment]
on peut virer numpy et scipy.

**Comment by cspaier** [comment]
Bien joué!

Je vais repartir d'une installe propre ou je vais juste rajouter pygame pour être sur qu'on ait pas des libs inutiles et lourdes qui trainent.

Ceux qui bossent en local et push en console (@al-coloic ) faudra probablement recloner.

**Comment by al-coloic** [comment]
Recloner.
Ca pèse encore 180 Mo le truc ! Y a pas moyen d'alléger ?

**Comment by al-coloic** [comment]
c'est le num #19, sorry
