### ISSUE TITLE
range avec python 3

### ISSUE THREAD

**Issue by al-coloic** [Pydiderot/pydiderotIDE#21]
paragraphe **Python's range() vs xrange() Functions**

[https://www.pythoncentral.io/pythons-range-function-explained/](https://www.pythoncentral.io/pythons-range-function-explained/)

La nouvelle fonction range dans python 3 construit un objet 'range' et pas 'list'. On peut l'utiliser dans les boucles.
Par exemple : 
`Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) `
`[GCC 7.3.0] on linux2`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> range(0,2)`
`[0, 1]`
et
`Python 3.6.7 (default, Oct 22 2018, 11:32:17) `
`[GCC 8.2.0] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> range(0,2)`
`range(0, 2)`

Du coup je propose de rajouter une fonction creer_liste(deb,fin,pas) avec que du float et de mettre une vrai fin et pas fin-1

**Comment by cspaier** [comment]
C'est clair qu'il nous faut une fonction comme ca pour simplifier les boucles `for` avec les élèves.

`lycée` a une fonction [intervalle](https://pydiderot.readthedocs.io/librairies/lycee/?highlight=intervalle#stats_proba.intervalle) qui répond au problème pour des entiers.

Il suffit peut-être de la modifier pour qu'elle accepte des `float`?

Par rapport à l'objet `range`, j'ai l'impression que c'est juste de l'optimisation mémoire: La liste n'est pas générée immédiatement.

La différence c'est qu'on peut pas le manipuler directement comme une liste (`append` par exemple). Dans nos cas il suffit d'en faire une liste `liste(range(début, fin, pas))` et on aura pas de souci.

**Comment by al-coloic** [comment]
c'est fait, fonction listes.series()
