### ISSUE TITLE
Rendre les librairies indépendantes

### ISSUE THREAD

**Issue by al-coloic** [Pydiderot/pydiderotIDE#22]
Je suis allé vite dans l'écriture de certaines fonctions.

Des fonctions de _stats_ appellent _listes_ qui appellent _fonctions_usuelles_.
Ce n'est pas très grave mais doit-on rendre ces libs indépendantes l'une de l'autre, ou conserve-t-on la lib générale _lycee_ comme un tout ?

**Comment by cspaier** [comment]
Je pense pas que ce soit un problème.

En l'état, on peut choisir d'importer une partie (`vecteurs` par exemple) ou la grande librairie `lycee` sans problème.

On peut aussi construire des librairies (`seconde`, `premiere`, ...) à la carte facilement.

La seule contrainte est que les fichiers doivent-êrte tous présents.

Un utilisateur à simplement à télécharger le zip avec [ce lien](https://pydiderot.readthedocs.io/_static/diderot.zip) et à laisser tous les fichiers. J'imagine qu'ajouter un fichier `README` à ce dossier ne ferait pas de mal.

Par contre j'envisage de mettre les lib `vecteurs`, `stats_proba`, ... dans un dossier `lycee_lib` pour faire du ménage.

**Comment by cspaier** [comment]
On est bon du coup? Je ferme?

**Comment by al-coloic** [comment]
yep
