### ISSUE TITLE
thonny 3 ne fonctionne pas au lycée

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#23]
Pour la formation de ce midi, j'ai du remettre une version 2.17.0. 

La version présente dans les branches `diderot` ou `thonny` se lance mais bloque au démarrage: La fenêtre est inutilisable et un sablier tourne.

On a pas de console au lycée donc il m'est impossible de savoir ce qui ce passe.

**Comment by al-coloic** [comment]
t'as demandé au tech ?

**Comment by cspaier** [comment]
Non. Mais comme c'était un peu le bazar, je veux rééssayer avec une version propre avant.

**Comment by cspaier** [comment]
Bon je viens de tester au lycée avec un thonny 3 tout propre et on a le même résultat. Fonctionne parfois mais la plupart du temps il "freeze" au démarrage.

Ca fonctionne sans problème sur mes VM windows 10 et windows 7 à la maison.

Je vais voir avec le référent informatique de l'établissement.

**Comment by byache** [comment]
Essai sur un windows7 avec un PC portable assez lent...
Le zip fait moins de 25 Mo
Dézippé : 67Mo, 2 minutes pour extraire les fichiers.
Lancement de thonny : 30s.
Après, ça marche... pas vu de pb particulier.

**Comment by cspaier** [comment]
\o/ Ca fonctionne!!!!

J'ai mis une nouvelle version toute propre au lycée. Fonctionne en B318 et au labo de math. J'ai laissé la vielle version (le raccourci est `Thonny - python (vielle version)` au cas ou il y ait des problèmes.

Je crois que le problème est qu' il y avait un morceau d’environnement python 3.6 dans mon dossier personnel avec des libs (pygame). Des trucs que j'avais installé avec pip. Il y a de grande chances que ca ne buggait que sur ma session ^^

Ce soir je up le nouveau dossier. Je vais tout supprimer pour repartir propre. Si vous avez des copies locales faudra re cloner.

**Comment by byache** [comment]
Testé en B317.
Effectivement : aucun problème :-)

**Comment by cspaier** [comment]
Merci du retour.

J'ai remis une version propre.

@al-coloic : il faut recloner.
