### ISSUE TITLE
librairie vecteurs dans la librairie graphique

### ISSUE THREAD

**Issue by zebobs** [Pydiderot/pydiderotIDE#24]
Il y a un import vecteurs dans la librairie graphique.
 A enlever ?

**Comment by al-coloic** [comment]
oui mais il faut réécrire
`def trace_vecteur(x, y, v, couleur=rouge, epaisseur=2):`

**Comment by al-coloic** [comment]
Le fait d'avoir virer numpy : on n'a plus la somme ni la multiplication de vecteurs.
Il nous faut remplacer ces deux fonctions #20

**Comment by al-coloic** [comment]
A faire avec les élèves je pense.
graphique corriger
