### ISSUE TITLE
Organisation du fichier TestLibrairies

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#28]
On veut un fichier qui permette de tester simplement nos fonctions maisons.

@al-coloic a bien bossé et on a déja du code qui test à peu près tout. Je fais cette issue pour qu'on se mette d'accord sur le "comment organiser le machin".

Jusqu'ici importer la librairie lançait tout les test à la suite. Je trouvais cela un peu lourd et difficile à utiliser. Du coup, dans [ce commit](https://github.com/cspaier/pydiderot/commit/ff1d389d8e568bc3fefcb70abc493b785f9703bb) j'ai mis les différents tests dans des fonctions `test_lycee`, `test_graphique`...

J'en ait profité pour y remettre les tests de `graphique` et `repere` (voir [ici](https://github.com/cspaier/pydiderot/commit/986fe0122c6b9d7b8001c1b7149a5d6507b4e0ad#commitcomment-31963333))

Maintenant, importer le module `TestLibrairies` ne lance aucun test mais les lignes suivantes afficheront les différents test possibles:

https://github.com/cspaier/pydiderot/blob/6991d91cd414c275f78b9ec6896577f285d57805/Thonny/Lib/site-packages/TestLibrairies.py#L201-L205

Ca vous va?
Si oui, il faudra supprimer les fichier `TestLibGraphique.py`, `TestLibRepere` et `TestLibrairies2`.

**Comment by al-coloic** [comment]
carrément !

**Comment by al-coloic** [comment]
mais je définirai les fonctions test dans les librairies correspondantes !

POO forever !

**Comment by cspaier** [comment]
Je voulais faire ca mais ca m'embêtait d'importer `tkinter` dans `couleurs` juste pour le test. Alors je sais pas trop.

Pour info, python a un systeme de tests bien propre ([unittest](https://docs.python.org/fr/3/library/unittest.html)). Jamais utilisé et flemme de m'y pencher.

**Comment by al-coloic** [comment]
fais simple.

**Comment by cspaier** [comment]
Yep.
Bon j'ai supprimé les fichiers inutiles et renommé le fichier en `test_librairies` pour être cohérent dans le format des noms de fichiers (on utilise snakecase partout).
