### ISSUE TITLE
renommer entree_tk -> entree ?

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#29]
Ca a été discuté pendant la formation. La lib  `entree_tk` est bien mal nommée. Bon, pour ceux qui connaissent tkinter ca a du sens, mais ils seront minoritaires parmi nos utilisateurs.

De souvenir le consensus portait sur `entree` comme nouveau nom.

Idées? Objections?

**Comment by byache** [comment]
Je vote pour "entree"

**Comment by al-coloic** [comment]
ça me va
