### ISSUE TITLE
doc formation à relire d'ici jeudi... avis aux amateurs

### ISSUE THREAD

**Issue by byache** [Pydiderot/pydiderotIDE#31]
C'est ici : docs > formation > enseignants2.md

Clément, si tu es par là et que tu veux ajouter ton grain de sel...
N'hésite pas !

Petit pb : je ne sais pas pourquoi mais il y a certains titres qui n'apparaissent pas

Il y a aussi le pdf à mettre dans le dossier static

+ qqs autres petits détails mais bon, c'est présentable. Tout sera à discuter jeudi...

**Comment by cspaier** [comment]
J'ai pas du tout participé à ca.

Ya encore du boulo ou on ferme?

**Comment by byache** [comment]
on peut fermer
