### ISSUE TITLE
Renommer les librairies ?

### ISSUE THREAD

**Issue by al-coloic** [Pydiderot/pydiderotIDE#4]
Pour qu'on puisse s'y retrouver plus facilement sur les sources entre les 3 librairies et peut être d'autres futures, ne serait-il pas judicieux de renommer les librairies ?

Par exemple : 
graphique en aixmarseille
lycée en amiens
et lycée graph en diderot

**Comment by cspaier** [comment]
Renommer oui, pour l'instant c'est confus. 

Par contre je pense que le nom doit venir de l'utilité de la lib et non du lieu d'origine. Je suis pas sur qu' utiliser `from  clermontferrand import *` pour charger une librairie graphique soit intuitif.

Pour l'origine, on va documenter de toute façon.


Je verais bien:
- graphique -> repere.
- lycee_graph -> graphique
- lycee -> lycee ?

A discuter. De toute façon faut appliquer ce choix pendant l'été pour pas chambouler les élèves.

**Comment by al-coloic** [comment]
Yep.

Je viens de me fader une bonne parti des nouveaux programmes et en STI2D ça va coder sévère ! Avec notamment les listes.

On va avoir besoin je pense de faire une librairie graphique, une librairie Seconde, une librairie Premiere STI2D. Et encore la taille du programme de STI2D risque de nous obliger à découper...
Plus l'enseignement Math de première général (pas lu), et ceux de Ter qui arrivent.

Ce que j'en dis au final, c'est pousser le graphique (presque fini), lire et adapter le nouveau de programme de seconde.

**Comment by cspaier** [comment]
Pourquoi t'as fermé?

Il faut toujours renommer `graphique` en `repere` et `grapique_dynamique` en `graphique` non?

**Comment by cspaier** [comment]
Et j'aimerai bien faire ca avant la formation de la rentrée. Des objections?
