### ISSUE TITLE
Portabilité

### ISSUE THREAD

**Issue by al-coloic** [Pydiderot/pydiderotIDE#5]
Je propose de se mettre d'accord sur un encodage de caractère, déclaré en début de fichier
1/ Cela augmentera la portabilité Unix/Windows
2/ Cela sensibilisera les élèves au problèmes

Sinon je propose UTF-8, mais cela obligera à ne pas mettre d'accent même dans les commentaire : saine discipline...

Du coup il faudrait réécrire les commentaires

**Comment by al-coloic** [comment]
bon les commentaires petre pas

**Comment by cspaier** [comment]
Bonne idée l'encodage. J'y connais rien par contre.

Pour les commentaires c'est pas énorme à faire: rechercher/remplacer.

Concernant la portabilité, l'idéal serait un moyen simple d'avoir le logiciel sous linux/macOS. Je vois pas de solution simple pour l'instant. Créer un plugin thonny semble la solution propre mais pénible à mettre en place. Un pis aller serait de distribuer un zip contenant les librairies du lycée pour simplifier la vie de l'utilisateur (un DL au lieu de 3).

**Comment by al-coloic** [comment]
la déclaration de l'encodage se fait en tet de fichier avec : 
`# -*- coding: utf-8 -*-`
par exemple. Je dis ça car j'ai eu des soucis avec mes codes écrits chez moi que je faisais tourner au lycée. Cela réglait le problème.

> Pour les commentaires c'est pas énorme à faire: rechercher/remplacer.

certes mais je crois que c'est inutile en fait.

Pour l'histoire du plugin on verra quand on sera inspecteur

**Comment by cspaier** [comment]
Du coup, il suffit de vérifier qu'on a bien mis `# -*- coding: utf-8 -*-` au début de chaque fichier et on ferme.

**Comment by al-coloic** [comment]
yop
