### ISSUE TITLE
Graphique dynamique

### ISSUE THREAD

**Issue by cspaier** [Pydiderot/pydiderotIDE#7]
L'idée serait d'amener les élèves à coder un object qui se déplace dans une fenetre.

Tkinter ne semble pas pertinent pour cet usage. Voici [un exemple](https://gist.github.com/cspaier/67a7908eb67c8e26da3a501b04fd114e) avec pygame.

Il faudrait construire une bibliothèque de fonctions utilisant pygame très simple à utiliser.

**Comment by cspaier** [comment]
Un début [ici](https://gist.github.com/cspaier/028c65ae9080c102733d51529087ffa9).

**Comment by cspaier** [comment]
Je pense à supprimer la librairie [lycee_graph](https://github.com/cspaier/thonny/blob/diderot/Thonny/Lib/site-packages/lycee_graph.py).

Good to you?

**Comment by al-coloic** [comment]
ouais carrément !

**Comment by byache** [comment]
Actuellement, le seul problème qui empêche cette librairie de fonctionner correctement 'd'après mes attentes) est un problème de type "import circulaire" : je ne veux garder dans le fichier manipulé par les élèves quasiment qu'une fonction "iteration" et mettre tout le reste du code dans la librairie. Problème : le fichier de l'élève va importer la librairie mais cette même librairie devra à un moment faire appel à l'import de "iteration". Les solutions que j'ai pour le moment ne sont pas très satisfaisantes. Mais rien ne dit qu'en essayant de rendre un fonctionnement avec pygame "présentable pour les élèves" on ne tombe pas sur le même problème. Donc je demande le statu-quo pour le moment...

**Comment by byache** [comment]
A part ça : le code de cette librairie est également présent dans "graphique". Donc si on garde lycee_graph, il faudra lui faire utiliser les fonctions de "graphique" plutôt que d'avoir deux versions...
Perso je m'étais embêté à tout mettre en anglais, et vous vous vous êtes embêtés à tout mettre en français :-) Comme vous êtes deux, je suis minoritaire... Mais je ne sais pas si un choix est meilleur : à reconsidérer dans un ou deux ans ;-) ?

**Comment by cspaier** [comment]
@byache : ok pour le statut quo. As tu jeté un oeil a [cela](https://gist.github.com/cspaier/028c65ae9080c102733d51529087ffa9)?

C'est testé et ca fonctionne. Le code de la librarie et l'utilisation élève sont simples.

```python
from graph_dynamique import *
import time

x = 0
y = 0
v_x = 1
v_y = 1

creer_fenetre()

while 1:
    evenements()
    
    trace_cercle(x,y)
    time.sleep(0.1)
    trace_cercle(x,y,couleur=blanc)
    x += v_x
    y += v_y
```

Pour la question Anglais our Francais, je ne sais pas. On peut continuer en francais et voir à l'usage dans quelques temps.

**Comment by al-coloic** [comment]
plus de reperage en seconde. C'est un acquis du collège : cf. [cycle 4 page 8](http://maths.ac-noumea.nc/IMG/pdf/programme_cycle_4_rentree_2018.pdf)

Par contre on aura : 

> Base orthonormée. Coordonnées d’un vecteur. Expression de la norme d’un vecteur.

et les déterminans (?!)

acitivité pédagogique : lire/trouver la base d'affichage de pydiderot (héritée de pygame) ?
Et écrire la 'matrice' de changement de base ? (x en x-milieu de fenetre et y en -y+milieu de fenetre ?)

**Comment by cspaier** [comment]
Mouais, tu troll. En pratique on en fera.

J'entends que tu lève la question du repérage inversé. Je pensais mettre l'origine en bas à gauche pour faire simple.

**Comment by al-coloic** [comment]
Pour info : [https://www.apmep.fr/IMG/pdf/Brevet_metropole_Reunion_28_juin2018.pdf](https://www.apmep.fr/IMG/pdf/Brevet_metropole_Reunion_28_juin2018.pdf)

**Comment by al-coloic** [comment]
et les programmes de 2018, [lire page 7](http://maths.ac-noumea.nc/IMG/pdf/programme_cycle_4_rentree_2018.pdf), **Comprendre et utiliser la notion de fonction**.

**Comment by cspaier** [comment]
Les discussions sur les programmes sont intéressantes mais je pense qu'on peut fermer dans le mesure où on a une librairie fonctionelle et [documentée](https://pydiderot.readthedocs.io/librairies/graphique/#graphique.creer_fenetre).

**Comment by byache** [comment]
Je pense qu'on peut virer lycee_graph...
